spring:
  profiles:
    active: dev
  application:
    name: partnermatching


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456

  # Redis配置
  redis:
    port: 6379
    host: localhost
    database: 0

  # 发送邮件设置
  mail:
    host: smtp.qq.com # 此处使用的是qq邮箱进行邮件发送
    username: 1349190697@qq.com # 发送邮件的账号（也就是本人账号）
    password: vhsgwnzoxdpzfhbg # 账号秘钥（注意这不是登录你QQ邮箱的密码！该秘钥在开启SMTP服务时会给出。）
    default-encoding: UTF-8 #编码风格
    port: 465
    # 解决线上环境不能发送邮件的问题（阿里云服务器，不支持默认端口25来发送邮件）
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        smtp.socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory



  # 设置session超时时间
  session:
    timeout: 86400
    store-type: redis


server:
  port: 8080
  #address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        secure: true
        same-site: none


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0

# 支付宝沙箱参数配置
alipay:
  appId: 9021000132652403
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQChp0dmoOOXPj7VmXBHemyjEqPfpVCaQ+B3xwBOCUneb9GtpY963436qamgIHXiNUOq8ctk6FWIDsFvOwqi6lhRjNpFct5Hf//KP++wGLbithC24gOHPlPI6JZRzmLJT8dStWkY/JMIck9AVJBWHkpBlPpM/QEkvWb19DUXNH6X5rAzFIm/vhDhMCmiq6IK8ojLuszaTiI2slxMCiv0vYA7E2yPx+y6c9IZwmnzz5ztCty80NXjA/DPsKCyIk4Q+A2YJ8fPzl4S2E7yyV4mer8ltfcVfeSKyki/pTnRo0doLhBmlgEv+GOzDiYmF5z5SZ98dV3Zxb0kuBs6lP+3Qa3FAgMBAAECggEAL9wBtK3Pk/iWy9CIwHDLdyBOqikciv+rlmqxeWkgmJ2Me5e3ug4zz9GpacIShK12YkcCC9cJc6XCuTbGuGMfUM2d1c/jZVHNHkj9oqo+gzKaEjsqBkF6ttG9p2yuLKHVBnS1L/OfaHHHauleblC7dV0xGdgSHZmBwTHTAhLFpBzrhJuEi6LlMhnYrms/YZq5aZQVb01VF0VVo1O+WvQ1Fkifv/4hhacjQlTy81Ny8m+oJruabOZedZ0QXroW1avA4l85KLFCJrFUs+DNEmc28lLe7oVxqDlMwpv9ZCSZh+fGzbvSpN3ECWAohYD+3PBWVKGL7bxgI7EP3hXeUZKfAQKBgQDtr35dRcz8HLeRLlgfNkt66jBhvdDLrGorg0VOs5PxP9UhYF3zNOPDClWAFYnGIc7Z/tv9GbnoFKwlDirJoMUTrZTmA9I8YDeP6/NF2jUvLSpcS9BvSZWr7eqk4j7xAsf0L4BKvTHlTDV/5MqeG9AQPQGazUQTbVQLhiPoNw4HQQKBgQCuHABXryIqFriMhg9GccbMYgCl8ADIdgK56YmWq+f/cG9O7/QD15fiSZFkCh+0i1DFIoXpNLq0aLG7QDBjeFT7jPmrDoQR3aWLJVIT+xl2xti4IC9BspSp9iWptrK58zqCKD8mSIy4H3cOVR/QpeL2KQLXeByFSYytg65K7K6phQKBgEZJQyDp5zgWdeIkxkJUl/V9E1mT/A5+qda8Nt6TFAifS7NW//FPjpq6j5YUyG0iyjyEtSEfXm5WzqEWk2iUdjLffcyXDLB183hH2eSqJlgRDxnEAZsnM29oJ58imGJE5EQ9V77CO+MGqjtruM8QgnKK19KjKKJmDhhqTmv4+9kBAoGAHLywbciRSgMgCMmjwcvLtTZDxx+68VtRDeB2/jB3hVjIdm3yh6PRBN+BqNJm80S/WxpcoeY7HsXc9/wbQH++/xoAp3Qo5k4AIdxSFMwwIsOlR5bAVgaktPzUsJNgIoL72DnOWoJE/6rp2qrAKo8Gy/xu5KOFiZZfKtB+Nw2jsoUCgYEA3yMR93gZW5Guvoz97VSN3iJjCwEGcJTa43fkXhFqmu6iN4ST4erNPT6+uAugdvGrsAVSwsaqoNyzlJf69xNcRI1D43kfqDh1lDFa3ohZDiHTH466qBRhwtx6fpHRkabDHCjLzLUwZUGd38ahtLTSAK6CHrYHaMrtM3Qu13V+xyY=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhDZlAOlAaBWU2nBtUQTyEnMc08EcitStel2tDVcQq7RpSZrT1mU8c/gA0bkpX4lC3JTWY2a48NLUIGRYtQv5W6Wb6louCaIfQ0rJLsZ3cIDP9gmH8jJXWIqaRS95e+A1okw9G5O+C4hjvB4LdgR1+C8pFOEU/1nl9m84qe8eWUtyxQlMMf5utvQZ9DfTKgMpGWciyF3RSjvBmN+SQyrYo5R23W6c6ZkJfd+MmCH3uSRqzun/O+H3p98ag0014U4s121jEJ32dRo4nTzPDXXNEqCAGPoRegsVa8NRriomHIyKTbvgaQqIXaGCcHlDsATTv5cEHe/y7xAOnYjfYUTxSQIDAQAB
  notifyUrl: http://www.iyaya.icu/alipay/notify

