spring:
  profiles:
    active: dev
  application:
    name: partnermatching


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456

  # Redis配置
  redis:
    port: 6379
    host: localhost
    database: 0

  # 发送邮件设置
  mail:
    host: smtp.qq.com # 此处使用的是qq邮箱进行邮件发送
    username: 1349190697@qq.com # 发送邮件的账号（也就是本人账号）
    password: vhsgwnzoxdpzfhbg # 账号秘钥（注意这不是登录你QQ邮箱的密码！该秘钥在开启SMTP服务时会给出。）
    default-encoding: UTF-8 #编码风格
    port: 465
    # 解决线上环境不能发送邮件的问题（阿里云服务器，不支持默认端口25来发送邮件）
    properties:
      mail:
        smtp:
          ssl:
            enable: true
        smtp.socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory



  # 设置session超时时间
  session:
    timeout: 86400
    store-type: redis


server:
  port: 8080
  #address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        secure: true
        same-site: none


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    db-config:
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0

